version: '3'
services:
  mysqldb:
    image: "mysql:5.6"
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: coffeehousems
       
  discovery:
    image: f9dcb458a294
    build: EurekaServer
    ports:
      - 8762:8761  
  user-service:
    image: a170725ede57
    build: user-service
    depends_on:
      - discovery
      - mysqldb 
    ports:
      - 8086:8086 
  coffee-service:
    image: 1c2ba7237e1f
    build: coffee-service
    depends_on:
      - discovery
      - mysqldb 
    ports:
      - 8080:8080
      
  note-service:
    image: 0dcabe7ae39d
    build: note-service
    depends_on:
      - discovery
      - mysqldb 
    ports:
      - 8087:8087
  order-service:
    image: 0d289aeea96f
    build: order-service
    depends_on:
      - discovery
      - mysqldb 
    ports:
      - 8089:8089
  employe-service:
    image: 645a013473bc
    build: employe-service
    depends_on:
      - discovery
      - mysqldb 
    ports:
      - 8085:8085
  api-gateway:
    image: 9f39be698498
    build: api-gateway
    depends_on:
      - discovery
    ports:
      - 8199:8099
    
      
  