server:
  port: 8099

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://host.docker.internal:8086/
        predicates:
            - Path=/userms/**
      - id: employe-service
        uri: http://host.docker.internal:8085/
        predicates:
            - Path=/employems/**
      - id: coffee-service
        uri: http://host.docker.internal:8080/
        predicates:
          - Path=/coffeems/**
      - id: note-service
        uri: http://host.docker.internal:8087/
        predicates:
          - Path=/notems/**
      - id: order-service
        uri: http://host.docker.internal:8089/
        predicates:
          - Path=/orderms/**
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

  
      